/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package pl.futurecollars.invoicing

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new App()

        when:
        def result = app.greeting

        then:
        result != null
    }

    def "should print correct greeting"() {
        given:
        def outputStream = new ByteArrayOutputStream()
        System.setOut(new PrintStream(outputStream))

        when:
        App.main(new String[0])

        then:
        String output = outputStream.toString().trim()
        output == "Hello World!"
    }
}
