/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package pl.futurecollars.invoicing

import pl.futurecollars.invoicing.model.Vat
import spock.lang.Specification

class AppTest extends Specification {

    def "should print correct greeting"() {
        given:
        def outputStream = new ByteArrayOutputStream()
        System.setOut(new PrintStream(outputStream))

        when:
        App.main(new String[0])

        then:
        String output = outputStream.toString().trim()
        output == "Hello World!"
    }

    def "should print correct greeting"() {
        given:
        def outputStream = new ByteArrayOutputStream()
        System.setOut(new PrintStream(outputStream))

        when:
        App.main(new String[0])

        then:
        String output = outputStream.toString().trim()
        output == "Hello World!"
    }
}
