name: CI

on:
  push:
    branches: [ 'task_[0-9]+\/.*', 'master' ]
  pull_request:
    branches: [ 'task_[0-9]+\/.*', 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Make executables
        run: chmod +x ./gradlew
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build
